apiVersion: batch/v1
kind: CronJob
metadata:
  name: kill-argocd-job
  namespace: argocd-oom-with-jobs
spec:
  jobTemplate:
    metadata:
      name: kill-argocd-job
    spec:
      template:
        spec:
          containers:
          - image: alpine
            name: kill-argocd-job
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
